### ISSUE TITLE
Executes two commands

### ISSUE THREAD

**Issue by burt0096** [fiveseven808/AmazonDashButtonHack#11]
Initially set up the button with one command.  Worked fine.  Tried to change the button to execute a different command.  It now executes both the first and second commands.  Is there any way to flush previous associations?

**Comment by fiveseven808** [comment]
Try and check your system tray for a green square with a white H on it, that should be the services running keeping an eye out for your buttons. Hover your mouse over them to figure out which service does what. I believe it should tell you what program you're running or what nickname you've named it or something. Once you found the one you want to close, just right click it, and exit! 

Let me know if this helps! Thanks for using this!

**Comment by burt0096** [comment]
That worked!  I can't believe I didn't think to check the system tray myself.   Thank you, and thanks for a great approach to this.  I tried using some of the python programs that are out there for this until I realized that they were designed primarily for Linux.  Your script works perfectly for me.
