### ISSUE TITLE
Windows Defender reports this as Malware

### ISSUE THREAD

**Issue by palodich** [fiveseven808/AmazonDashButtonHack#4]
Trojan:Win32/Rundas!plock

Category: Trojan

Description: This program is dangerous and executes commands from an attacker.

Recommended action: Remove this software immediately.

Items: 
file:D:\AmazonDashButtonHack-master\bin\AmazonButton_Discovery.exe

Get more information about this item online.

**Comment by fiveseven808** [comment]
False positive. Looks like you've cloned the repo. You're welcome to look through and compile from source. I haven't figured out why it shows up as a false positive though, but I've packaged things as an EXE so people don't have to download AHK.
