### ISSUE TITLE
Virus Detected- Google and Windows Defender.

### ISSUE THREAD

**Issue by keithschm** [fiveseven808/AmazonDashButtonHack#5]
Category: Trojan

Description: This program is dangerous and executes commands from an attacker.

Recommended action: Remove this software immediately.

Items: 
containerfile:C:\ProgramData\Microsoft\Windows Defender\LocalCopy{ED0FD1A5-CC5F-4E3F-B068-DA742AD9B210}-AmazonDashButtonHack-master.zip
file:C:\ProgramData\Microsoft\Windows Defender\LocalCopy{ED0FD1A5-CC5F-4E3F-B068-DA742AD9B210}-AmazonDashButtonHack-master.zip->AmazonDashButtonHack-master/bin/AmazonButton_Discovery.exe
file:C:\ProgramData\Microsoft\Windows Defender\LocalCopy{ED0FD1A5-CC5F-4E3F-B068-DA742AD9B210}-AmazonDashButtonHack-master.zip->AmazonDashButtonHack-master/prod/old/AmazonButton_Discovery 0901 1853.zip->AmazonButton_Discovery.exe
webfile:C:\ProgramData\Microsoft\Windows Defender\LocalCopy{ED0FD1A5-CC5F-4E3F-B068-DA742AD9B210}-AmazonDashButtonHack-master.zip|https://codeload.github.com/fiveseven808/AmazonDashButtonHack/zip/master

**Comment by fiveseven808** [comment]
False positive obviously. A report has already been submitted to Microsoft for review.
