### ISSUE TITLE
Anyone know how to use it with wemo? 

### ISSUE THREAD

**Issue by BitPopCoin** [fiveseven808/AmazonDashButtonHack#6]
What else are you using it with?

**Comment by BitpopCoin** [comment]
Ok I think I got it, this is cool!

https://github.com/fiveseven808/AmazonDashButtonHack
http://www.allware.com.mx/Software.aspx?Pr=AllWemo

C:\Users\Mike\Desktop\AmazonButton_Discovery_160715_2304\AmazonButton_v4.0.exe 192.168.0.227 "C:\Users\Mike\Desktop\AllWemo_2_10_setup\AllWemo.exe -ip:192.168.0.133 -action:toggle"

Using Amazon Dash button to toggle Wemo outlets.

**Comment by BitPopCoin** [comment]
Ok I think I got it, this is cool!

https://github.com/fiveseven808/AmazonDashButtonHack
http://www.allware.com.mx/Software.aspx?Pr=AllWemo

C:\Users\User\Desktop\AmazonButton_Discovery_160715_2304\AmazonButton_v4.0.exe 192.168.0.157 "C:\Users\User\Desktop\AllWemo_2_10_setup\AllWemo.exe -ip:192.168.0.123 -action:toggle"

Using Amazon Dash button to toggle Wemo outlets.

**Comment by BitPopCoin** [comment]
So I have to use the startup folder right? There's no service?

**Comment by fiveseven808** [comment]
Awesome! Glad you got it! Sorry, I guess I missed your issue. Yes, you'll have to use the startup folder, at least that's how I use it. I run multiple buttons so I run multiple instances of the program to manage them. 

Very cool though! I didn't know there was a program out there that managed wemo devices! I want to try this now!
